services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'nimbusserver.aos.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://nimbusserver.aos.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 8930
    ports:
      - '8929:8929'
      - '8930:22'
    container_name: gitlab
    networks:
      - demo-net

networks:
  demo-net:
    external: true         
