services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: 'nimbusserver.aos.com' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://nimbusserver.aos.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 8930
    ports:
      - '8929:8929'
      - '8930:22'
    container_name: gitlab
    networks:
      - demo-net

  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/home/demo/gitlab-runner
    restart: unless-stopped
    container_name: gitlab-runner
    networks:
      - demo-net

networks:
  demo-net:
    external: true

volumes:
  gitlab-runner-config:
    external: true

